name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Build documentation
      run: sphinx -E -W source build
